apiVersion: v1
kind: Service
metadata:
  name: etl-gardener-tcpinfo-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: etl-gardener-tcpinfo
  sessionAffinity: None
  type: LoadBalancer
